return {
    "9cb7afbe-4b83-46ac-a3ea-35a742489f0e", -- asdasd fred
    "BDD9E88B-F115-4100-9D8C-35E07AA062F6", -- french
    "e5547716-0092-419f-86d7-199df70cfede", -- shawn2drippy
    "1B8E75C1-B7FA-4726-AE10-931CD19D4BCC", -- lays
    "F9FEDC35-BF2D-499B-95DB-9BB8A16880F3", --1604
    "d", 
    "d", 
    "d", 
    "d",
    "d",
    "d",
    "d",
    "d",
    "d",
    "d",
    "d",
    "d",
    "d",
}
